var faucetbox = [ 
         { l: 'http://pingubitcoin.top/faucet/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 300, p: 300, v:'200-1500' },
         { l: 'http://faucet.btcaway.com/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 10, p: 100, v:'100-10000' },
         { l: 'http://getyourbitco.in/111570', t: 5, p: 250, v:'Вывод в ручном режиме без минималки' },
         { l: 'http://timeforbitco.in/86176', t: 5, p: 100, v:'Накопительный. Вывод в ручном режиме при достижении 20000 сатошей' },
         { l: 'http://weatherx.co.in/72589', t: 5, p: 50, v:'Зависит от температуры. Вывод в ручном режиме при достижении 10000 сатошей' },
         { l: 'http://chronox.co.in/130989', t: 5, p: 23, v:'Вывод в ручном режиме при достижении 25000 сатошей' },
         { l: 'http://sunbtc.space/93273', t: 5, p: 25, v:'За сутки 403 сатоши. Вывод в ручном режиме при достижении 20000 сатошей' },
         { l: 'http://fasterclick.net/?uid=131193', t: 10, p: 100, v:'От 100 до 5000 сатоши. Еженедельный вывод при достижении 20000 сатошей' },
         { l: 'http://elenafaucets.com/freebitcoin01/?ref=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', k:'elenafaucets.com-1', t: 60, p: 275, v:'От 275 до 450 сатоши. Вывод в ручном режиме при достижении 6000 сатошей' },
         { l: 'http://elenafaucets.com/freebitcoin02/?ref=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', k:'elenafaucets.com-2', t: 60, p: 300, v:'От 300 до 500 сатоши. Вывод в ручном режиме при достижении 6000 сатошей' },
         { l: 'http://elenafaucets.com/freebitcoin03/?ref=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', k:'elenafaucets.com-3', t: 10, p: 150, v:'Вывод в ручном режиме при достижении 6000 сатошей' },
         { l: 'http://elenafaucets.com/freebitcoin04/?ref=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', k:'elenafaucets.com-4', t: 60, p: 250, v:'От 250 до 400 сатоши. Вывод в ручном режиме при достижении 6000 сатошей' },
         { l: 'http://icebitcoin.net/freebitcoin/?ref=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 60, p: 300, v:'От 300 до 10000 сатоши. Вывод в ручном режиме без минималки' },
         { l: 'http://infaucet.com/?id=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 5, p: 100, v:'Бонус до 300 сатоши. Вывод в ручном режиме без минималки' },
         { l: 'http://crazyfaucet.com/?id=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 5, p: 80, v:'Бонус. Вывод в ручном режиме без минималки' },
         { l: 'http://bitfaucet.co/?id=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 5, p: 100, v:'Бонус. Вывод в ручном режиме без минималки' },
         { l: 'http://bctec.ru/faucet/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 90, p: 90, v:'Бонус. Вывод в ручном режиме без минималки' },
         { l: 'http://satoshiki.ru/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 800, p: 600, v:'600-1200. Вывод сразу' },
         { l: 'http://coin-x.ru/btc/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 20, p: 150, v:'600-1200. Вывод сразу' },
         { l: 'http://allbtc.ru/faucet/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 1200, p: 650, v:'600-1200. Вывод сразу' },
         { l: 'http://freeclaimbtc.xyz/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 15, p: 300, v:'*!!! Вывод сразу' },
         { l: 'http://faucetgame.com/r/447570', t: 15, p: 250, v:'Вывод от 50000 сатошей' },
         { l: 'http://www.btcfaucet.xyz/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 120, p: 100, v:'Вывод сразу' },
         { l: 'http://www.bitcoinfaucet.pro/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 120, p: 100, v:'Вывод сразу' },
         { l: 'http://www.topfaucet.online/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 120, p: 100, v:'Вывод сразу' },
         { l: 'http://www.givemefreebitcoins.today/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 120, p: 100, v:'Вывод сразу' },
         { l: 'http://www.topfaucet.info/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 120, p: 100, v:'Вывод сразу' },
         { l: 'http://www.bestfaucet.pro/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 60, p: 100, v:'Вывод сразу' },
         { l: 'http://www.btcfaucetpro.com/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 60, p: 100, v:'Вывод сразу' },
         { l: 'http://www.freebitcoinfaucet.club/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 60, p: 150, v:'Вывод сразу' },
         { l: 'http://www.bestfaucetbitco.in/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 60, p: 100, v:'Вывод сразу' },
         { l: 'http://www.peakfaucet.com/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 30, p: 100, v:'Вывод сразу' },
         { l: 'http://www.topfaucet.net/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 15, p: 150, v:'Вывод сразу' },
         { l: 'http://www.earnfreebitco.in/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 15, p: 100, v:'Вывод сразу' },
         { l: 'http://www.givemefreebitco.in/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 15, p: 100, v:'Вывод сразу' },
         { l: 'http://www.freebitcoins4.me/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 15, p: 150, v:'Вывод сразу' },
         { l: 'http://www.freebitcoinfaucet.co.uk/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 15, p: 100, v:'Вывод сразу' },
         { l: 'http://www.bitcoinfaucetpro.com/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 15, p: 100, v:'Вывод сразу' },
         { l: 'http://www.play4bitco.in/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 15, p: 100, v:'Вывод сразу' },
         { l: 'http://www.freefaucetbitco.in/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 15, p: 100, v:'Вывод сразу' },
         { l: 'http://www.bitcoinsbitcoins.net/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 15, p: 100, v:'Вывод сразу' },
         { l: 'http://www.bestfaucet.org/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 15, p: 100, v:'Вывод сразу' },
         { l: 'http://www.fullbitcoins.com/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 5, p: 100, v:'Вывод сразу' },
         { l: 'http://bitcoinsstar.com/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 720, p: 1000, v:'Вывод сразу' },
         { l: 'http://megafaucetbox.xyz/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 720, p: 601, v:'Вывод сразу' },
         { l: 'http://playduck.xyz?ref=Z7QfDp0AD9', t: 5, p: 75, v:'Вывод по запросу от 100 сатошей' },
         
         ]

         // 
         // { l: 'http://givebtc.xyz/?r=1GiYJn6fnZPxmYWgWG6twEPuuHEQrXJ5D8', t: 7, p: 400, v:'Зависят от IP' },
         // http://coin-x.ru/list/
         // http://faucet-rotator.info/
         // http://www.favoritefaucets.com/